-- =========================================================
-- Proyecto: Café Nova
-- Script maestro de base de datos
-- Base de datos: Supabase / PostgreSQL
-- Archivo sugerido: docs/sql/00-cafe-nova-full-setup.sql
-- =========================================================

-- =========================================================
-- 1. TABLAS
-- =========================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  rol text not null default 'admin',
  activo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint profiles_rol_check
    check (rol in ('admin'))
);

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  activo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint categorias_nombre_unique unique (nombre)
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  categoria_id bigint not null references public.categorias(id),
  nombre text not null,
  descripcion text,
  precio numeric(10,2) not null,
  presentacion text not null,
  tipo_cafe text not null,
  imagen_url text,
  activo boolean not null default true,
  destacado boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint productos_precio_check
    check (precio >= 0),

  constraint productos_tipo_cafe_check
    check (tipo_cafe in ('molido', 'grano', 'otro'))
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  codigo_pedido text not null unique,
  nombre_cliente text not null,
  telefono text not null,
  correo text,
  direccion text,
  comentarios text,
  estado text not null default 'pendiente',
  total_estimado numeric(10,2) not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint pedidos_estado_check
    check (estado in ('pendiente', 'confirmado', 'en_preparacion', 'entregado', 'cancelado')),

  constraint pedidos_total_estimado_check
    check (total_estimado >= 0)
);

create table if not exists public.pedido_detalle (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  producto_id bigint not null references public.productos(id),
  nombre_producto text not null,
  precio_unitario numeric(10,2) not null,
  cantidad integer not null,
  subtotal numeric(10,2) not null,
  created_at timestamp with time zone not null default now(),

  constraint pedido_detalle_precio_unitario_check
    check (precio_unitario >= 0),

  constraint pedido_detalle_cantidad_check
    check (cantidad > 0),

  constraint pedido_detalle_subtotal_check
    check (subtotal >= 0)
);

-- Campo agregado posteriormente para notas internas del administrador
alter table public.pedidos
add column if not exists notas_admin text;

-- =========================================================
-- 2. FUNCIÓN PARA UPDATED_AT
-- =========================================================

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- =========================================================
-- 3. TRIGGERS UPDATED_AT
-- =========================================================

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_categorias_updated_at on public.categorias;
create trigger set_categorias_updated_at
before update on public.categorias
for each row
execute function public.set_updated_at();

drop trigger if exists set_productos_updated_at on public.productos;
create trigger set_productos_updated_at
before update on public.productos
for each row
execute function public.set_updated_at();

drop trigger if exists set_pedidos_updated_at on public.pedidos;
create trigger set_pedidos_updated_at
before update on public.pedidos
for each row
execute function public.set_updated_at();

-- =========================================================
-- 4. DATOS INICIALES
-- =========================================================

insert into public.categorias (nombre, descripcion, activo)
values
('Café molido', 'Café listo para preparar en casa u oficina.', true),
('Café en grano', 'Café para moler al momento y conservar mejor aroma.', true),
('Ediciones especiales', 'Lotes especiales o cafés de temporada.', true)
on conflict (nombre) do update
set
  descripcion = excluded.descripcion,
  activo = excluded.activo;

insert into public.productos (
  categoria_id,
  nombre,
  descripcion,
  precio,
  presentacion,
  tipo_cafe,
  imagen_url,
  activo,
  destacado
)
select
  c.id,
  'Café Nova Molido 250g',
  'Café artesanal molido, ideal para consumo diario.',
  1500,
  '250g',
  'molido',
  '/images/products/cafe-nova-molido-250g.png',
  true,
  true
from public.categorias c
where c.nombre = 'Café molido'
  and not exists (
    select 1 from public.productos p
    where p.nombre = 'Café Nova Molido 250g'
  );

insert into public.productos (
  categoria_id,
  nombre,
  descripcion,
  precio,
  presentacion,
  tipo_cafe,
  imagen_url,
  activo,
  destacado
)
select
  c.id,
  'Café Nova Molido 500g',
  'Presentación familiar de café molido fresco.',
  3900,
  '500g',
  'molido',
  '/images/products/cafe-nova-molido-500g.png',
  true,
  false
from public.categorias c
where c.nombre = 'Café molido'
  and not exists (
    select 1 from public.productos p
    where p.nombre = 'Café Nova Molido 500g'
  );

insert into public.productos (
  categoria_id,
  nombre,
  descripcion,
  precio,
  presentacion,
  tipo_cafe,
  imagen_url,
  activo,
  destacado
)
select
  c.id,
  'Café Nova en Grano 250g',
  'Café en grano para quienes prefieren moler al momento.',
  2500,
  '250g',
  'grano',
  '/images/products/cafe-nova-grano-250g.png',
  true,
  true
from public.categorias c
where c.nombre = 'Café en grano'
  and not exists (
    select 1 from public.productos p
    where p.nombre = 'Café Nova en Grano 250g'
  );

insert into public.productos (
  categoria_id,
  nombre,
  descripcion,
  precio,
  presentacion,
  tipo_cafe,
  imagen_url,
  activo,
  destacado
)
select
  c.id,
  'Café Nova en Grano 500g',
  'Mayor frescura y aroma en presentación de 500g.',
  5200,
  '500g',
  'grano',
  '/images/products/cafe-nova-grano-500g.png',
  true,
  false
from public.categorias c
where c.nombre = 'Café en grano'
  and not exists (
    select 1 from public.productos p
    where p.nombre = 'Café Nova en Grano 500g'
  );

-- =========================================================
-- 5. FUNCIÓN AUXILIAR DE ADMIN
-- =========================================================

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and rol = 'admin'
      and activo = true
  );
$$;

-- =========================================================
-- 6. ACTIVAR ROW LEVEL SECURITY
-- =========================================================

alter table public.profiles enable row level security;
alter table public.categorias enable row level security;
alter table public.productos enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_detalle enable row level security;

-- =========================================================
-- 7. LIMPIAR POLICIES EXISTENTES
-- =========================================================

-- Profiles
drop policy if exists "Admins can read profiles" on public.profiles;

-- Categorias
drop policy if exists "Public can read active categorias" on public.categorias;
drop policy if exists "Admins can read categorias" on public.categorias;
drop policy if exists "Admins can insert categorias" on public.categorias;
drop policy if exists "Admins can update categorias" on public.categorias;
drop policy if exists "Admins can delete categorias" on public.categorias;
drop policy if exists "Admins can manage categorias" on public.categorias;

-- Productos
drop policy if exists "Public can read active productos" on public.productos;
drop policy if exists "Admins can read productos" on public.productos;
drop policy if exists "Admins can insert productos" on public.productos;
drop policy if exists "Admins can update productos" on public.productos;
drop policy if exists "Admins can delete productos" on public.productos;
drop policy if exists "Admins can manage productos" on public.productos;

-- Pedidos
drop policy if exists "Public can create pedidos" on public.pedidos;
drop policy if exists "Admins can read pedidos" on public.pedidos;
drop policy if exists "Admins can update pedidos" on public.pedidos;

-- Pedido detalle
drop policy if exists "Public can create pedido_detalle" on public.pedido_detalle;
drop policy if exists "Admins can read pedido_detalle" on public.pedido_detalle;

-- =========================================================
-- 8. POLICIES: PROFILES
-- =========================================================

create policy "Admins can read profiles"
on public.profiles
for select
to authenticated
using (public.is_admin());

-- =========================================================
-- 9. POLICIES: CATEGORIAS
-- =========================================================

create policy "Public can read active categorias"
on public.categorias
for select
to anon, authenticated
using (activo = true);

create policy "Admins can read categorias"
on public.categorias
for select
to authenticated
using (public.is_admin());

create policy "Admins can insert categorias"
on public.categorias
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update categorias"
on public.categorias
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete categorias"
on public.categorias
for delete
to authenticated
using (public.is_admin());

-- =========================================================
-- 10. POLICIES: PRODUCTOS
-- =========================================================

create policy "Public can read active productos"
on public.productos
for select
to anon, authenticated
using (activo = true);

create policy "Admins can read productos"
on public.productos
for select
to authenticated
using (public.is_admin());

create policy "Admins can insert productos"
on public.productos
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update productos"
on public.productos
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete productos"
on public.productos
for delete
to authenticated
using (public.is_admin());

-- =========================================================
-- 11. POLICIES: PEDIDOS
-- =========================================================

create policy "Public can create pedidos"
on public.pedidos
for insert
to anon, authenticated
with check (estado = 'pendiente');

create policy "Admins can read pedidos"
on public.pedidos
for select
to authenticated
using (public.is_admin());

create policy "Admins can update pedidos"
on public.pedidos
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- =========================================================
-- 12. POLICIES: PEDIDO_DETALLE
-- =========================================================

create policy "Public can create pedido_detalle"
on public.pedido_detalle
for insert
to anon, authenticated
with check (true);

create policy "Admins can read pedido_detalle"
on public.pedido_detalle
for select
to authenticated
using (public.is_admin());

-- =========================================================
-- 13. RPC PARA CREAR PEDIDO PÚBLICO
-- =========================================================

create or replace function public.crear_pedido_publico(
  p_nombre_cliente text,
  p_telefono text,
  p_correo text,
  p_direccion text,
  p_comentarios text,
  p_items jsonb
)
returns table (
  pedido_id bigint,
  codigo_pedido text,
  total_estimado numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido_id bigint;
  v_codigo_pedido text;
  v_total numeric(10,2) := 0;
  v_item jsonb;
  v_producto record;
  v_cantidad integer;
  v_subtotal numeric(10,2);
begin
  if p_nombre_cliente is null or length(trim(p_nombre_cliente)) = 0 then
    raise exception 'El nombre del cliente es obligatorio';
  end if;

  if p_telefono is null or length(trim(p_telefono)) = 0 then
    raise exception 'El teléfono es obligatorio';
  end if;

  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido debe tener al menos un producto';
  end if;

  v_codigo_pedido := 'CN-' || to_char(now(), 'YYYYMMDD-HH24MISS');

  insert into public.pedidos (
    codigo_pedido,
    nombre_cliente,
    telefono,
    correo,
    direccion,
    comentarios,
    estado,
    total_estimado,
    notas_admin
  )
  values (
    v_codigo_pedido,
    trim(p_nombre_cliente),
    trim(p_telefono),
    nullif(trim(coalesce(p_correo, '')), ''),
    nullif(trim(coalesce(p_direccion, '')), ''),
    nullif(trim(coalesce(p_comentarios, '')), ''),
    'pendiente',
    0,
    null
  )
  returning id into v_pedido_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_cantidad := coalesce((v_item->>'cantidad')::integer, 0);

    if v_cantidad <= 0 then
      raise exception 'La cantidad debe ser mayor a cero';
    end if;

    select
      id,
      nombre,
      precio
    into v_producto
    from public.productos
    where id = (v_item->>'producto_id')::bigint
      and activo = true;

    if not found then
      raise exception 'Producto no encontrado o inactivo';
    end if;

    v_subtotal := v_producto.precio * v_cantidad;
    v_total := v_total + v_subtotal;

    insert into public.pedido_detalle (
      pedido_id,
      producto_id,
      nombre_producto,
      precio_unitario,
      cantidad,
      subtotal
    )
    values (
      v_pedido_id,
      v_producto.id,
      v_producto.nombre,
      v_producto.precio,
      v_cantidad,
      v_subtotal
    );
  end loop;

  update public.pedidos
  set total_estimado = v_total
  where id = v_pedido_id;

  return query
  select
    v_pedido_id,
    v_codigo_pedido,
    v_total;
end;
$$;

grant execute on function public.crear_pedido_publico(
  text,
  text,
  text,
  text,
  text,
  jsonb
) to anon, authenticated;

-- =========================================================
-- 14. VALIDACIONES DE APOYO
-- =========================================================

-- Ver tablas principales
select
  'categorias' as tabla,
  count(*) as total
from public.categorias
union all
select
  'productos' as tabla,
  count(*) as total
from public.productos
union all
select
  'pedidos' as tabla,
  count(*) as total
from public.pedidos
union all
select
  'pedido_detalle' as tabla,
  count(*) as total
from public.pedido_detalle;

-- =========================================================
-- 15. NOTA PARA CREAR USUARIO ADMIN
-- =========================================================
--
-- Este script NO crea usuarios en auth.users.
--
-- Para crear un administrador:
--
-- 1. Crear usuario desde Supabase:
--    Authentication > Users > Add user
--
-- 2. Copiar el UUID del usuario creado.
--
-- 3. Ejecutar:
--
-- insert into public.profiles (
--   id,
--   nombre,
--   rol,
--   activo
-- )
-- values (
--   'UUID_DEL_USUARIO_AUTH',
--   'Christian Vega',
--   'admin',
--   true
-- );
--
-- El usuario debe existir primero en auth.users.
-- =========================================================